import { describe, it, expect, beforeEach, afterAll } from "vitest";
import path from "node:path";
import {
  verifyLeanSource,
  clearVerificationCache,
  verificationCacheSize,
  resetLeanAvailability,
} from "@/lib/lean/sandbox";
import { shutdownReplPool } from "@/lib/lean/repl";

// Drive verifyLeanSource through the fake REPL (see fixtures/fake-repl.mjs).
const FAKE = path.resolve(__dirname, "fixtures/fake-repl.mjs");

beforeEach(() => {
  process.env.LEAN_REPL_COMMAND = `${process.execPath} ${FAKE}`;
  process.env.LEAN_SERVER_MODE = "server";
  delete process.env.LEAN_ALLOW_NATIVE_DECIDE;
  clearVerificationCache();
  resetLeanAvailability();
  shutdownReplPool();
});

afterAll(() => {
  shutdownReplPool();
  delete process.env.LEAN_REPL_COMMAND;
});

const HEADER = "-- Generated by lean-math-agent. Do not edit lakefile.\nimport Mathlib\n\n";

describe("verifyLeanSource verdicts (fake REPL)", () => {
  it("accepts a complete proof with only standard axioms and returns the signature", async () => {
    const src = HEADER + "theorem t (n : Nat) : n + 0 = n := by\n  simp -- propext";
    const r = await verifyLeanSource("s1", src, { theoremName: "t" });
    expect(r.ok).toBe(true);
    expect(r.status).toBe("ok");
    expect(r.backend).toBe("repl");
    expect(r.axioms?.axioms).toEqual(["propext"]);
    expect(r.axioms?.disallowed).toEqual([]);
    expect(r.signature).toBe("∀ (n : Nat), n + 0 = n");
    expect(r.log).toBe("ok");
  });

  it("rejects sorry/admit textually before Lean runs when a complete proof is required", async () => {
    const r = await verifyLeanSource("s2", HEADER + "theorem t : True := by\n  admit", { theoremName: "t" });
    expect(r.ok).toBe(false);
    expect(r.backend).toBe("none");
    expect(r.rejected).toMatch(/sorry/);
  });

  it("allows sorry for prefix verification and returns the goal at the sorry", async () => {
    const r = await verifyLeanSource("s3", HEADER + "theorem t (n : Nat) : n + 0 = n := by\n  sorry", {
      allowSorry: true,
    });
    expect(r.ok).toBe(true);
    expect(r.goals).toEqual(["n : Nat\n⊢ n + 0 = n"]);
    // Line numbers are mapped back to the full file (3 header lines).
    expect(r.sorries[0].line).toBe(2 + 3);
  });

  it("fails a proof whose axioms include sorryAx even if the text hides it", async () => {
    // The fake reports sorryAx for anything mentioning `sorry` in a comment?
    // No — comments are stripped textually; simulate a hidden sorry through
    // the axioms probe by allowing sorry text and disabling the textual gate.
    const src = HEADER + "theorem t : True := by\n  trivial\n-- sorry mentioned only here";
    const r = await verifyLeanSource("s4", src, { theoremName: "t" });
    // fake-repl marks `sorry` anywhere in cmd (including the comment), so the
    // axioms probe reports sorryAx and the sorries list is non-empty:
    expect(r.ok).toBe(false);
    expect(r.axioms?.usesSorry).toBe(true);
    expect(r.log).toMatch(/sorry|sorryAx/);
  });

  it("fails on native_decide unless LEAN_ALLOW_NATIVE_DECIDE=true", async () => {
    const src = HEADER + "theorem t : (2:Nat) + 2 = 4 := by\n  native_decide";
    const r1 = await verifyLeanSource("s5", src, { theoremName: "t" });
    expect(r1.ok).toBe(false);
    expect(r1.axioms?.usesNative).toBe(true);
    expect(r1.log).toMatch(/disallowed axioms/);

    process.env.LEAN_ALLOW_NATIVE_DECIDE = "true";
    clearVerificationCache();
    const r2 = await verifyLeanSource("s5", src, { theoremName: "t" });
    expect(r2.ok).toBe(true);
  });

  it("reports Lean errors with file-relative positions", async () => {
    const r = await verifyLeanSource("s6", HEADER + "theorem t (n : Nat) : n + 0 = n := by\n  error_here", {
      allowSorry: true,
    });
    expect(r.ok).toBe(false);
    expect(r.messages[0]).toMatchObject({ severity: "error", line: 5, column: 2 });
    expect(r.log).toContain("Verify.lean:5:2: error: unsolved goals");
  });

  it("locks the statement: fails when the signature differs from the validated one", async () => {
    const src = HEADER + "theorem t (n : Nat) : 0 + n = n := by\n  simp -- OTHER_STATEMENT";
    const r = await verifyLeanSource("s7", src, {
      theoremName: "t",
      expectedSignature: "∀ (n : Nat), n + 0 = n",
    });
    expect(r.ok).toBe(false);
    expect(r.signatureMatch).toBe(false);
    expect(r.log).toMatch(/differs from the validated formalization/);
    const good = await verifyLeanSource("s7b", HEADER + "theorem t (n : Nat) : n + 0 = n := by\n  simp", {
      theoremName: "t",
      expectedSignature: "∀ (n : Nat),   n + 0 = n",
    });
    expect(good.ok).toBe(true);
    expect(good.signatureMatch).toBe(true);
  });

  it("rejects forbidden commands before contacting Lean", async () => {
    const r = await verifyLeanSource("s8", HEADER + "theorem t : True := trivial\n#eval IO.println \"x\"", {
      theoremName: "t",
    });
    expect(r.ok).toBe(false);
    expect(r.backend).toBe("none");
    expect(r.rejected).toContain("#eval");
  });

  it("caches results per (source, options)", async () => {
    clearVerificationCache();
    const src = HEADER + "theorem t : True := by\n  trivial";
    await verifyLeanSource("s9", src, { allowSorry: true });
    expect(verificationCacheSize()).toBe(1);
    const again = await verifyLeanSource("s9", src, { allowSorry: true });
    expect(again.durationMs).toBe(0);
    await verifyLeanSource("s9", src, { allowSorry: false });
    expect(verificationCacheSize()).toBe(2);
  });

  it("reports a timeout as a failed verdict instead of falling back", async () => {
    process.env.LEAN_BUILD_TIMEOUT_MS = "300";
    shutdownReplPool();
    try {
      const r = await verifyLeanSource("s10", HEADER + "theorem t : True := by\n  SLEEP", { allowSorry: true });
      expect(r.ok).toBe(false);
      expect(r.backend).toBe("repl");
      expect(r.log).toMatch(/timed out/);
    } finally {
      delete process.env.LEAN_BUILD_TIMEOUT_MS;
      shutdownReplPool();
    }
  });
});
