import type { ProofStep } from "../types";

export const LEAN_HEADER = `-- Generated by lean-math-agent. Do not edit lakefile.
`;

export function stepCodesUpTo(steps: ProofStep[], stepIndex: number): string[] {
  return steps
    .filter((s) => s.index <= stepIndex)
    .sort((a, b) => a.index - b.index)
    .map((s) => s.lean_code)
    .filter(Boolean);
}

export function assembleLeanSource(opts: {
  theoremName: string;
  theoremType: string;
  stepCodes: string[];
  /** Append trailing `sorry` for incomplete prefixes during step repair verifies. */
  appendSorry?: boolean;
}): string {
  const parts = opts.stepCodes.map((c) => c.trim()).filter(Boolean);
  if (opts.appendSorry) {
    parts.push("sorry");
  }
  const body = parts.join("\n\n");
  // Final verify must never silently succeed via empty/`sorry` body.
  // Use `fail` so lake rejects empty assemblies; repair path uses appendSorry.
  const tacticBody = body || (opts.appendSorry ? "sorry" : "fail");
  return `${LEAN_HEADER}theorem ${opts.theoremName} ${opts.theoremType} := by
${indent(tacticBody)}
`;
}

function indent(s: string): string {
  return s
    .split("\n")
    .map((line) => (line.length ? `  ${line}` : line))
    .join("\n");
}
