export const LEAN_HEADER = `-- Generated by lean-math-agent. Do not edit lakefile.
`;

export function assembleLeanSource(opts: {
  theoremName: string;
  theoremType: string;
  stepCodes: string[];
}): string {
  const body = opts.stepCodes.map((c) => c.trim()).filter(Boolean).join("\n\n");
  return `${LEAN_HEADER}theorem ${opts.theoremName} ${opts.theoremType} := by
${indent(body || "sorry")}
`;
}

function indent(s: string): string {
  return s
    .split("\n")
    .map((line) => (line.length ? `  ${line}` : line))
    .join("\n");
}
