/**
 * Curated seed of Mathlib lemmas for premise retrieval when no built index
 * (`npm run premises:build`) is present. Names are real Mathlib
 * declarations; the statements are simplified (typeclass binders omitted)
 * — they are hints for the prover, which Lean verifies anyway.
 *
 * Coverage: the lemmas competition-style proofs reach for most often —
 * order/inequalities, squares and absolute values, division, powers and
 * roots, exp/log/trig, ℕ/ℤ arithmetic and divisibility, parity, primes,
 * modular arithmetic, casts, finite sums/products and counting, logic.
 */
export const PREMISE_SEED: ReadonlyArray<readonly [name: string, type: string]> = [
  // ── Squares, absolute value ─────────────────────────────────────────
  ["sq_nonneg", "∀ (a : α), 0 ≤ a ^ 2"],
  ["mul_self_nonneg", "∀ (a : α), 0 ≤ a * a"],
  ["pow_two_nonneg", "∀ (a : α), 0 ≤ a ^ 2"],
  ["sq_abs", "∀ (a : α), |a| ^ 2 = a ^ 2"],
  ["abs_nonneg", "∀ (a : α), 0 ≤ |a|"],
  ["abs_pos", "0 < |a| ↔ a ≠ 0"],
  ["abs_mul_abs_self", "∀ (a : α), |a| * |a| = a * a"],
  ["abs_mul_self", "∀ (a : α), |a * a| = a * a"],
  ["abs_mul", "∀ (a b : α), |a * b| = |a| * |b|"],
  ["abs_le", "|a| ≤ b ↔ -b ≤ a ∧ a ≤ b"],
  ["abs_lt", "|a| < b ↔ -b < a ∧ a < b"],
  ["abs_sub_comm", "∀ (a b : α), |a - b| = |b - a|"],
  ["abs_sub_abs_le_abs_sub", "∀ (a b : α), |a| - |b| ≤ |a - b|"],
  ["abs_sub_le_iff", "|a - b| ≤ c ↔ a - b ≤ c ∧ b - a ≤ c"],
  ["abs_sub_lt_iff", "|a - b| < c ↔ a - b < c ∧ b - a < c"],
  ["abs_eq_abs", "|a| = |b| ↔ a = b ∨ a = -b"],
  ["abs_eq", "0 ≤ b → (|a| = b ↔ a = b ∨ a = -b)"],
  ["abs_of_nonneg", "0 ≤ a → |a| = a"],
  ["abs_of_neg", "a < 0 → |a| = -a"],
  ["abs_of_pos", "0 < a → |a| = a"],
  ["le_abs_self", "∀ (a : α), a ≤ |a|"],
  ["neg_abs_le", "∀ (a : α), -|a| ≤ a"],
  ["abs_le_abs", "a ≤ b → -b ≤ a → |a| ≤ |b|"],
  ["sq_le_sq", "a ^ 2 ≤ b ^ 2 ↔ |a| ≤ |b|"],
  ["sq_lt_sq", "a ^ 2 < b ^ 2 ↔ |a| < |b|"],
  ["sq_le_sq'", "-b ≤ a → a ≤ b → a ^ 2 ≤ b ^ 2"],
  ["sq_lt_sq'", "-b < a → a < b → a ^ 2 < b ^ 2"],
  ["abs_le_of_sq_le_sq'", "a ^ 2 ≤ b ^ 2 → 0 ≤ b → -b ≤ a ∧ a ≤ b"],
  ["pow_le_pow_left", "0 ≤ a → a ≤ b → ∀ (n : ℕ), a ^ n ≤ b ^ n"],
  ["pow_lt_pow_left", "a < b → 0 ≤ a → n ≠ 0 → a ^ n < b ^ n"],
  ["pow_le_pow_right₀", "1 ≤ a → n ≤ m → a ^ n ≤ a ^ m"],
  ["pow_le_one₀", "0 ≤ a → a ≤ 1 → a ^ n ≤ 1"],
  ["one_le_pow₀", "1 ≤ a → 1 ≤ a ^ n"],
  ["add_pow_two", "∀ (a b : α), (a + b) ^ 2 = a ^ 2 + 2 * a * b + b ^ 2"],
  ["add_sq", "∀ (a b : α), (a + b) ^ 2 = a ^ 2 + 2 * a * b + b ^ 2"],
  ["sub_sq", "∀ (a b : α), (a - b) ^ 2 = a ^ 2 - 2 * a * b + b ^ 2"],
  ["sq_sub_sq", "∀ (a b : α), a ^ 2 - b ^ 2 = (a + b) * (a - b)"],
  ["mul_self_abs", "∀ (a : α), |a| * |a| = a * a"],
  ["sq", "∀ (a : α), a ^ 2 = a * a"],
  ["pow_two", "∀ (a : α), a ^ 2 = a * a"],
  ["two_mul", "∀ (a : α), 2 * a = a + a"],
  ["mul_two", "∀ (a : α), a * 2 = a + a"],
  ["two_mul_le_add_sq", "∀ (a b : α), 2 * a * b ≤ a ^ 2 + b ^ 2"],
  ["four_mul_le_sq_add", "∀ (a b : α), 4 * a * b ≤ (a + b) ^ 2"],
  ["neg_sq", "∀ (a : α), (-a) ^ 2 = a ^ 2"],
  ["neg_pow", "∀ (a : α) (n : ℕ), (-a) ^ n = (-1) ^ n * a ^ n"],
  ["mul_self_eq_zero", "a * a = 0 ↔ a = 0"],
  ["pow_eq_zero_iff", "n ≠ 0 → (a ^ n = 0 ↔ a = 0)"],
  ["sq_eq_zero'", "a ^ 2 = 0 ↔ a = 0"],
  ["mul_eq_zero", "a * b = 0 ↔ a = 0 ∨ b = 0"],
  ["sub_eq_zero", "a - b = 0 ↔ a = b"],
  ["sq_eq_sq_iff_abs_eq_abs", "a ^ 2 = b ^ 2 ↔ |a| = |b|"],

  // ── Order: positivity, monotonicity ─────────────────────────────────
  ["mul_pos", "0 < a → 0 < b → 0 < a * b"],
  ["mul_nonneg", "0 ≤ a → 0 ≤ b → 0 ≤ a * b"],
  ["mul_pos_of_neg_of_neg", "a < 0 → b < 0 → 0 < a * b"],
  ["mul_nonneg_of_nonpos_of_nonpos", "a ≤ 0 → b ≤ 0 → 0 ≤ a * b"],
  ["mul_nonpos_of_nonneg_of_nonpos", "0 ≤ a → b ≤ 0 → a * b ≤ 0"],
  ["add_pos", "0 < a → 0 < b → 0 < a + b"],
  ["add_nonneg", "0 ≤ a → 0 ≤ b → 0 ≤ a + b"],
  ["add_pos_of_pos_of_nonneg", "0 < a → 0 ≤ b → 0 < a + b"],
  ["div_pos", "0 < a → 0 < b → 0 < a / b"],
  ["div_nonneg", "0 ≤ a → 0 ≤ b → 0 ≤ a / b"],
  ["inv_pos", "0 < a⁻¹ ↔ 0 < a"],
  ["pow_pos", "0 < a → ∀ (n : ℕ), 0 < a ^ n"],
  ["pow_nonneg", "0 ≤ a → ∀ (n : ℕ), 0 ≤ a ^ n"],
  ["sub_nonneg", "0 ≤ a - b ↔ b ≤ a"],
  ["sub_pos", "0 < a - b ↔ b < a"],
  ["sub_neg", "a - b < 0 ↔ a < b"],
  ["sub_nonpos", "a - b ≤ 0 ↔ a ≤ b"],
  ["neg_nonpos", "-a ≤ 0 ↔ 0 ≤ a"],
  ["neg_neg_iff_pos", "-a < 0 ↔ 0 < a"],
  ["mul_le_mul", "a ≤ b → c ≤ d → 0 ≤ c → 0 ≤ b → a * c ≤ b * d"],
  ["mul_lt_mul", "a < c → b ≤ d → 0 < b → 0 ≤ c → a * b < c * d"],
  ["mul_lt_mul'", "a ≤ c → b < d → 0 ≤ b → 0 < c → a * b < c * d"],
  ["mul_le_mul_of_nonneg_left", "b ≤ c → 0 ≤ a → a * b ≤ a * c"],
  ["mul_le_mul_of_nonneg_right", "b ≤ c → 0 ≤ a → b * a ≤ c * a"],
  ["mul_lt_mul_of_pos_left", "b < c → 0 < a → a * b < a * c"],
  ["mul_lt_mul_of_pos_right", "b < c → 0 < a → b * a < c * a"],
  ["mul_le_mul_left", "0 < c → (c * a ≤ c * b ↔ a ≤ b)"],
  ["mul_le_mul_right", "0 < c → (a * c ≤ b * c ↔ a ≤ b)"],
  ["mul_lt_mul_left", "0 < c → (c * a < c * b ↔ a < b)"],
  ["mul_self_le_mul_self", "0 ≤ a → a ≤ b → a * a ≤ b * b"],
  ["mul_self_lt_mul_self", "0 ≤ a → a < b → a * a < b * b"],
  ["mul_self_le_mul_self_iff", "0 ≤ a → 0 ≤ b → (a ≤ b ↔ a * a ≤ b * b)"],
  ["abs_le_abs_of_sq_le_sq", "a ^ 2 ≤ b ^ 2 → |a| ≤ |b|"],
  ["le_of_sub_nonneg", "0 ≤ a - b → b ≤ a"],
  ["sub_le_sub", "a ≤ b → c ≤ d → a - d ≤ b - c"],
  ["add_le_add", "a ≤ b → c ≤ d → a + c ≤ b + d"],
  ["add_lt_add", "a < b → c < d → a + c < b + d"],
  ["add_le_add_left", "b ≤ c → ∀ (a : α), a + b ≤ a + c"],
  ["add_le_add_right", "b ≤ c → ∀ (a : α), b + a ≤ c + a"],
  ["le_add_of_nonneg_right", "0 ≤ b → a ≤ a + b"],
  ["le_add_of_nonneg_left", "0 ≤ b → a ≤ b + a"],
  ["lt_add_of_pos_right", "∀ (a : α), 0 < b → a < a + b"],
  ["le_div_iff₀", "0 < c → (a ≤ b / c ↔ a * c ≤ b)"],
  ["div_le_iff₀", "0 < c → (a / c ≤ b ↔ a ≤ b * c)"],
  ["lt_div_iff₀", "0 < c → (a < b / c ↔ a * c < b)"],
  ["div_lt_iff₀", "0 < c → (a / c < b ↔ a < b * c)"],
  ["div_le_div_of_nonneg_left", "0 ≤ a → 0 < b → b ≤ c → a / c ≤ a / b"],
  ["div_le_div_of_nonneg_right", "a ≤ b → 0 ≤ c → a / c ≤ b / c"],
  ["div_le_one", "0 < b → (a / b ≤ 1 ↔ a ≤ b)"],
  ["one_le_div", "0 < b → (1 ≤ a / b ↔ b ≤ a)"],
  ["div_lt_one", "0 < b → (a / b < 1 ↔ a < b)"],
  ["one_lt_div", "0 < b → (1 < a / b ↔ b < a)"],
  ["inv_le_inv₀", "0 < a → 0 < b → (a⁻¹ ≤ b⁻¹ ↔ b ≤ a)"],
  ["one_div_le_one_div_of_le", "0 < a → a ≤ b → 1 / b ≤ 1 / a"],
  ["one_div_lt_one_div_of_lt", "0 < a → a < b → 1 / b < 1 / a"],
  ["le_of_lt", "a < b → a ≤ b"],
  ["le_of_eq", "a = b → a ≤ b"],
  ["lt_of_le_of_lt", "a ≤ b → b < c → a < c"],
  ["lt_of_lt_of_le", "a < b → b ≤ c → a < c"],
  ["le_trans", "a ≤ b → b ≤ c → a ≤ c"],
  ["lt_trans", "a < b → b < c → a < c"],
  ["le_antisymm", "a ≤ b → b ≤ a → a = b"],
  ["lt_irrefl", "∀ (a : α), ¬a < a"],
  ["lt_of_le_of_ne", "a ≤ b → a ≠ b → a < b"],
  ["eq_or_lt_of_le", "a ≤ b → a = b ∨ a < b"],
  ["lt_trichotomy", "∀ (a b : α), a < b ∨ a = b ∨ b < a"],
  ["le_total", "∀ (a b : α), a ≤ b ∨ b ≤ a"],
  ["le_or_lt", "∀ (a b : α), a ≤ b ∨ b < a"],
  ["lt_or_le", "∀ (a b : α), a < b ∨ b ≤ a"],
  ["not_le", "¬a ≤ b ↔ b < a"],
  ["not_lt", "¬a < b ↔ b ≤ a"],
  ["ne_of_gt", "a > b → a ≠ b"],
  ["ne_of_lt", "a < b → a ≠ b"],
  ["max_le", "a ≤ c → b ≤ c → max a b ≤ c"],
  ["le_max_left", "∀ (a b : α), a ≤ max a b"],
  ["le_max_right", "∀ (a b : α), b ≤ max a b"],
  ["min_le_left", "∀ (a b : α), min a b ≤ a"],
  ["min_le_right", "∀ (a b : α), min a b ≤ b"],
  ["le_min", "a ≤ b → a ≤ c → a ≤ min b c"],

  // ── Field arithmetic ────────────────────────────────────────────────
  ["div_add_div", "∀ (a c : α), b ≠ 0 → d ≠ 0 → a / b + c / d = (a * d + b * c) / (b * d)"],
  ["div_add_div_same", "∀ (a b c : α), a / c + b / c = (a + b) / c"],
  ["div_sub_div_same", "∀ (a b c : α), a / c - b / c = (a - b) / c"],
  ["div_div", "∀ (a b c : α), a / b / c = a / (b * c)"],
  ["div_mul_eq_mul_div", "∀ (a b c : α), a / b * c = a * c / b"],
  ["mul_div_assoc", "∀ (a b c : α), a * b / c = a * (b / c)"],
  ["div_self", "a ≠ 0 → a / a = 1"],
  ["mul_inv_cancel₀", "a ≠ 0 → a * a⁻¹ = 1"],
  ["mul_div_cancel_left₀", "∀ (b : α), a ≠ 0 → a * b / a = b"],
  ["mul_div_cancel_right₀", "∀ (a : α), b ≠ 0 → a * b / b = a"],
  ["div_mul_cancel₀", "∀ (a : α), b ≠ 0 → a / b * b = a"],
  ["eq_div_iff", "c ≠ 0 → (a = b / c ↔ a * c = b)"],
  ["div_eq_iff", "c ≠ 0 → (a / c = b ↔ a = b * c)"],
  ["div_eq_div_iff", "b ≠ 0 → d ≠ 0 → (a / b = c / d ↔ a * d = c * b)"],
  ["one_div", "∀ (a : α), 1 / a = a⁻¹"],
  ["div_pow", "∀ (a b : α) (n : ℕ), (a / b) ^ n = a ^ n / b ^ n"],
  ["mul_left_cancel₀", "a ≠ 0 → a * b = a * c → b = c"],
  ["mul_right_cancel₀", "b ≠ 0 → a * b = c * b → a = c"],
  ["sub_add_cancel", "∀ (a b : α), a - b + b = a"],
  ["add_sub_cancel_right", "∀ (a b : α), a + b - b = a"],
  ["add_sub_cancel_left", "∀ (a b : α), a + b - a = b"],
  ["sub_eq_add_neg", "∀ (a b : α), a - b = a + -b"],
  ["neg_neg", "∀ (a : α), - -a = a"],
  ["sub_self", "∀ (a : α), a - a = 0"],
  ["mul_comm", "∀ (a b : α), a * b = b * a"],
  ["mul_assoc", "∀ (a b c : α), a * b * c = a * (b * c)"],
  ["add_comm", "∀ (a b : α), a + b = b + a"],
  ["add_assoc", "∀ (a b c : α), a + b + c = a + (b + c)"],
  ["mul_add", "∀ (a b c : α), a * (b + c) = a * b + a * c"],
  ["add_mul", "∀ (a b c : α), (a + b) * c = a * c + b * c"],
  ["mul_sub", "∀ (a b c : α), a * (b - c) = a * b - a * c"],
  ["sub_mul", "∀ (a b c : α), (a - b) * c = a * c - b * c"],
  ["pow_succ", "∀ (a : α) (n : ℕ), a ^ (n + 1) = a ^ n * a"],
  ["pow_zero", "∀ (a : α), a ^ 0 = 1"],
  ["pow_one", "∀ (a : α), a ^ 1 = a"],
  ["pow_add", "∀ (a : α) (m n : ℕ), a ^ (m + n) = a ^ m * a ^ n"],
  ["pow_mul", "∀ (a : α) (m n : ℕ), a ^ (m * n) = (a ^ m) ^ n"],
  ["mul_pow", "∀ (a b : α) (n : ℕ), (a * b) ^ n = a ^ n * b ^ n"],
  ["one_pow", "∀ (n : ℕ), 1 ^ n = 1"],
  ["zero_pow", "n ≠ 0 → 0 ^ n = 0"],
  ["mul_one", "∀ (a : α), a * 1 = a"],
  ["one_mul", "∀ (a : α), 1 * a = a"],
  ["mul_zero", "∀ (a : α), a * 0 = 0"],
  ["zero_mul", "∀ (a : α), 0 * a = 0"],
  ["add_zero", "∀ (a : α), a + 0 = a"],
  ["zero_add", "∀ (a : α), 0 + a = a"],
  ["eq_neg_iff_add_eq_zero", "a = -b ↔ a + b = 0"],
  ["neg_eq_iff_eq_neg", "-a = b ↔ a = -b"],
  ["eq_sub_iff_add_eq", "a = b - c ↔ a + c = b"],
  ["sub_eq_iff_eq_add", "a - b = c ↔ a = c + b"],

  // ── Square roots, exp / log, trig ───────────────────────────────────
  ["Real.sqrt_nonneg", "∀ (x : ℝ), 0 ≤ √x"],
  ["Real.sq_sqrt", "0 ≤ a → √a ^ 2 = a"],
  ["Real.sqrt_sq", "0 ≤ a → √(a ^ 2) = a"],
  ["Real.mul_self_sqrt", "0 ≤ a → √a * √a = a"],
  ["Real.sqrt_mul_self", "0 ≤ a → √(a * a) = a"],
  ["Real.sqrt_le_sqrt", "x ≤ y → √x ≤ √y"],
  ["Real.sqrt_lt_sqrt", "0 ≤ x → x < y → √x < √y"],
  ["Real.sqrt_le_iff", "√x ≤ y ↔ 0 ≤ y ∧ x ≤ y ^ 2"],
  ["Real.sqrt_lt'", "0 < y → (√x < y ↔ x < y ^ 2)"],
  ["Real.lt_sqrt", "0 ≤ y → (y < √x ↔ y ^ 2 < x)"],
  ["Real.le_sqrt", "0 ≤ y → (y ≤ √x ↔ y ^ 2 ≤ x)"],
  ["Real.sqrt_le_sqrt_iff", "0 ≤ y → (√x ≤ √y ↔ x ≤ y)"],
  ["Real.sqrt_pos", "0 < √x ↔ 0 < x"],
  ["Real.sqrt_eq_zero'", "√x = 0 ↔ x ≤ 0"],
  ["Real.sqrt_eq_iff_mul_self_eq", "0 ≤ x → 0 ≤ y → (√x = y ↔ y * y = x)"],
  ["Real.sqrt_mul", "0 ≤ x → ∀ (y : ℝ), √(x * y) = √x * √y"],
  ["Real.sqrt_div", "0 ≤ x → ∀ (y : ℝ), √(x / y) = √x / √y"],
  ["Real.sqrt_one", "√1 = 1"],
  ["Real.sqrt_zero", "√0 = 0"],
  ["Real.sqrt_eq_one", "√x = 1 ↔ x = 1"],
  ["Real.exp_pos", "∀ (x : ℝ), 0 < Real.exp x"],
  ["Real.exp_nonneg", "∀ (x : ℝ), 0 ≤ Real.exp x"],
  ["Real.add_one_le_exp", "∀ (x : ℝ), x + 1 ≤ Real.exp x"],
  ["Real.add_one_lt_exp", "x ≠ 0 → x + 1 < Real.exp x"],
  ["Real.exp_zero", "Real.exp 0 = 1"],
  ["Real.exp_add", "∀ (x y : ℝ), Real.exp (x + y) = Real.exp x * Real.exp y"],
  ["Real.exp_ne_zero", "∀ (x : ℝ), Real.exp x ≠ 0"],
  ["Real.exp_lt_exp", "Real.exp x < Real.exp y ↔ x < y"],
  ["Real.exp_le_exp", "Real.exp x ≤ Real.exp y ↔ x ≤ y"],
  ["Real.exp_one_gt_d9", "2.7182818283 < Real.exp 1"],
  ["Real.exp_one_lt_d9", "Real.exp 1 < 2.7182818286"],
  ["Real.log_exp", "∀ (x : ℝ), Real.log (Real.exp x) = x"],
  ["Real.exp_log", "0 < x → Real.exp (Real.log x) = x"],
  ["Real.log_one", "Real.log 1 = 0"],
  ["Real.log_zero", "Real.log 0 = 0"],
  ["Real.log_mul", "x ≠ 0 → y ≠ 0 → Real.log (x * y) = Real.log x + Real.log y"],
  ["Real.log_div", "x ≠ 0 → y ≠ 0 → Real.log (x / y) = Real.log x - Real.log y"],
  ["Real.log_pow", "∀ (n : ℕ) (x : ℝ), Real.log (x ^ n) = n * Real.log x"],
  ["Real.log_rpow", "0 < x → ∀ (y : ℝ), Real.log (x ^ y) = y * Real.log x"],
  ["Real.log_le_sub_one_of_pos", "0 < x → Real.log x ≤ x - 1"],
  ["Real.log_pos", "1 < x → 0 < Real.log x"],
  ["Real.log_nonneg", "1 ≤ x → 0 ≤ Real.log x"],
  ["Real.log_neg", "0 < x → x < 1 → Real.log x < 0"],
  ["Real.log_lt_log", "0 < x → x < y → Real.log x < Real.log y"],
  ["Real.log_le_log", "0 < x → x ≤ y → Real.log x ≤ Real.log y"],
  ["Real.log_le_log_iff", "0 < x → 0 < y → (Real.log x ≤ Real.log y ↔ x ≤ y)"],
  ["Real.log_lt_log_iff", "0 < x → 0 < y → (Real.log x < Real.log y ↔ x < y)"],
  ["Real.rpow_natCast", "∀ (x : ℝ) (n : ℕ), x ^ (n : ℝ) = x ^ n"],
  ["Real.rpow_le_rpow", "0 ≤ x → x ≤ y → 0 ≤ z → x ^ z ≤ y ^ z"],
  ["Real.rpow_le_rpow_left_iff", "1 < x → (x ^ y ≤ x ^ z ↔ y ≤ z)"],
  ["Real.rpow_add", "0 < x → ∀ (y z : ℝ), x ^ (y + z) = x ^ y * x ^ z"],
  ["Real.rpow_pos_of_pos", "0 < x → ∀ (y : ℝ), 0 < x ^ y"],
  ["Real.rpow_nonneg", "0 ≤ x → ∀ (y : ℝ), 0 ≤ x ^ y"],
  ["Real.sin_sq_add_cos_sq", "∀ (x : ℝ), Real.sin x ^ 2 + Real.cos x ^ 2 = 1"],
  ["Real.cos_sq_add_sin_sq", "∀ (x : ℝ), Real.cos x ^ 2 + Real.sin x ^ 2 = 1"],
  ["Real.sin_le_one", "∀ (x : ℝ), Real.sin x ≤ 1"],
  ["Real.neg_one_le_sin", "∀ (x : ℝ), -1 ≤ Real.sin x"],
  ["Real.cos_le_one", "∀ (x : ℝ), Real.cos x ≤ 1"],
  ["Real.neg_one_le_cos", "∀ (x : ℝ), -1 ≤ Real.cos x"],
  ["Real.abs_sin_le_one", "∀ (x : ℝ), |Real.sin x| ≤ 1"],
  ["Real.abs_cos_le_one", "∀ (x : ℝ), |Real.cos x| ≤ 1"],
  ["Real.sin_two_mul", "∀ (x : ℝ), Real.sin (2 * x) = 2 * Real.sin x * Real.cos x"],
  ["Real.cos_two_mul", "∀ (x : ℝ), Real.cos (2 * x) = 2 * Real.cos x ^ 2 - 1"],
  ["Real.cos_sq'", "∀ (x : ℝ), Real.cos x ^ 2 = 1 - Real.sin x ^ 2"],
  ["Real.sin_sq", "∀ (x : ℝ), Real.sin x ^ 2 = 1 - Real.cos x ^ 2"],
  ["Real.sin_add", "∀ (x y : ℝ), Real.sin (x + y) = Real.sin x * Real.cos y + Real.cos x * Real.sin y"],
  ["Real.cos_add", "∀ (x y : ℝ), Real.cos (x + y) = Real.cos x * Real.cos y - Real.sin x * Real.sin y"],
  ["Real.sin_sub", "∀ (x y : ℝ), Real.sin (x - y) = Real.sin x * Real.cos y - Real.cos x * Real.sin y"],
  ["Real.cos_sub", "∀ (x y : ℝ), Real.cos (x - y) = Real.cos x * Real.cos y + Real.sin x * Real.sin y"],
  ["Real.sin_pi", "Real.sin π = 0"],
  ["Real.cos_pi", "Real.cos π = -1"],
  ["Real.sin_pi_div_two", "Real.sin (π / 2) = 1"],
  ["Real.cos_pi_div_two", "Real.cos (π / 2) = 0"],
  ["Real.pi_pos", "0 < π"],
  ["Real.pi_gt_three", "3 < π"],
  ["Real.pi_gt_314", "3.14 < π"],
  ["Real.pi_lt_315", "π < 3.15"],
  ["Real.sin_pos_of_pos_of_lt_pi", "0 < x → x < π → 0 < Real.sin x"],
  ["Real.cos_pos_of_mem_Ioo", "x ∈ Set.Ioo (-(π / 2)) (π / 2) → 0 < Real.cos x"],
  ["Real.tan_eq_sin_div_cos", "∀ (x : ℝ), Real.tan x = Real.sin x / Real.cos x"],
  ["Real.geom_mean_le_arith_mean2_weighted", "0 ≤ w₁ → 0 ≤ w₂ → 0 ≤ p₁ → 0 ≤ p₂ → w₁ + w₂ = 1 → p₁ ^ w₁ * p₂ ^ w₂ ≤ w₁ * p₁ + w₂ * p₂"],
  ["Real.geom_mean_le_arith_mean_weighted", "(∀ i ∈ s, 0 ≤ w i) → ∑ i ∈ s, w i = 1 → (∀ i ∈ s, 0 ≤ z i) → ∏ i ∈ s, z i ^ w i ≤ ∑ i ∈ s, w i * z i"],
  ["Finset.inner_mul_le_norm_mul_norm", "∀ (s : Finset ι) (f g : ι → ℝ), (∑ i ∈ s, f i * g i) ^ 2 ≤ (∑ i ∈ s, f i ^ 2) * ∑ i ∈ s, g i ^ 2"],
  ["Finset.sum_mul_sq_le_sq_mul_sq", "∀ (s : Finset ι) (f g : ι → α), (∑ i ∈ s, f i * g i) ^ 2 ≤ (∑ i ∈ s, f i ^ 2) * ∑ i ∈ s, g i ^ 2"],

  // ── ℕ arithmetic, order, division ───────────────────────────────────
  ["Nat.succ_le_of_lt", "n < m → n + 1 ≤ m"],
  ["Nat.succ_le_iff", "m + 1 ≤ n ↔ m < n"],
  ["Nat.lt_succ_iff", "m < n + 1 ↔ m ≤ n"],
  ["Nat.lt_iff_add_one_le", "m < n ↔ m + 1 ≤ n"],
  ["Nat.le_of_lt_succ", "m < n + 1 → m ≤ n"],
  ["Nat.lt_of_lt_of_le", "n < m → m ≤ k → n < k"],
  ["Nat.pos_of_ne_zero", "n ≠ 0 → 0 < n"],
  ["Nat.eq_zero_of_le_zero", "n ≤ 0 → n = 0"],
  ["Nat.eq_zero_or_pos", "∀ (n : ℕ), n = 0 ∨ 0 < n"],
  ["Nat.one_le_iff_ne_zero", "1 ≤ n ↔ n ≠ 0"],
  ["Nat.pos_iff_ne_zero", "0 < n ↔ n ≠ 0"],
  ["Nat.sub_add_cancel", "m ≤ n → n - m + m = n"],
  ["Nat.add_sub_cancel", "n + m - m = n"],
  ["Nat.add_sub_cancel_left", "n + m - n = m"],
  ["Nat.sub_le", "∀ (n m : ℕ), n - m ≤ n"],
  ["Nat.sub_lt", "0 < n → 0 < m → n - m < n"],
  ["Nat.sub_pos_of_lt", "m < n → 0 < n - m"],
  ["Nat.sub_eq_zero_of_le", "n ≤ m → n - m = 0"],
  ["Nat.le_sub_of_add_le", "k + m ≤ n → k ≤ n - m"],
  ["Nat.exists_eq_add_of_le", "m ≤ n → ∃ k, n = m + k"],
  ["Nat.exists_eq_add_of_lt", "m < n → ∃ k, n = m + k + 1"],
  ["Nat.le_antisymm", "n ≤ m → m ≤ n → n = m"],
  ["Nat.mul_self_le_mul_self", "m ≤ n → m * m ≤ n * n"],
  ["Nat.mul_self_lt_mul_self", "m < n → m * m < n * n"],
  ["Nat.mul_le_mul", "a ≤ b → c ≤ d → a * c ≤ b * d"],
  ["Nat.mul_le_mul_left", "∀ (k : ℕ), m ≤ n → k * m ≤ k * n"],
  ["Nat.mul_le_mul_right", "∀ (k : ℕ), m ≤ n → m * k ≤ n * k"],
  ["Nat.mul_lt_mul_of_lt_of_le", "a < b → c ≤ d → 0 < d → a * c < b * d"],
  ["Nat.pow_le_pow_left", "m ≤ n → ∀ (i : ℕ), m ^ i ≤ n ^ i"],
  ["Nat.pow_le_pow_right", "n > 0 → m ≤ k → n ^ m ≤ n ^ k"],
  ["Nat.pow_lt_pow_left", "a < b → n ≠ 0 → a ^ n < b ^ n"],
  ["Nat.pow_lt_pow_right", "1 < a → m < n → a ^ m < a ^ n"],
  ["Nat.one_le_two_pow", "1 ≤ 2 ^ n"],
  ["Nat.lt_two_pow_self", "n < 2 ^ n"],
  ["Nat.lt_pow_self", "1 < b → n < b ^ n"],
  ["Nat.pow_pos", "0 < b → 0 < b ^ n"],
  ["Nat.mod_lt", "∀ (x : ℕ), y > 0 → x % y < y"],
  ["Nat.mod_le", "∀ (x y : ℕ), x % y ≤ x"],
  ["Nat.div_add_mod", "∀ (m k : ℕ), k * (m / k) + m % k = m"],
  ["Nat.mod_add_div", "∀ (m k : ℕ), m % k + k * (m / k) = m"],
  ["Nat.div_mul_cancel", "b ∣ a → a / b * b = a"],
  ["Nat.mul_div_cancel'", "n ∣ m → n * (m / n) = m"],
  ["Nat.mul_div_le", "∀ (m n : ℕ), n * (m / n) ≤ m"],
  ["Nat.div_le_self", "∀ (n k : ℕ), n / k ≤ n"],
  ["Nat.div_lt_self", "0 < n → 1 < k → n / k < n"],
  ["Nat.div_pos", "b ≤ a → 0 < b → 0 < a / b"],
  ["Nat.le_div_iff_mul_le", "0 < k → (x ≤ y / k ↔ x * k ≤ y)"],
  ["Nat.div_lt_iff_lt_mul", "0 < k → (x / k < y ↔ x < y * k)"],
  ["Nat.div_mul_div_comm", "b ∣ a → d ∣ c → a / b * (c / d) = a * c / (b * d)"],
  ["Nat.mod_two_eq_zero_or_one", "∀ (n : ℕ), n % 2 = 0 ∨ n % 2 = 1"],
  ["Nat.mod_two_ne_zero", "¬n % 2 = 0 ↔ n % 2 = 1"],
  ["Nat.mod_mod_of_dvd", "∀ (n : ℕ), m ∣ k → n % k % m = n % m"],
  ["Nat.mod_mod_self", "n % m % m = n % m"],
  ["Nat.mod_self", "∀ (n : ℕ), n % n = 0"],
  ["Nat.mod_eq_of_lt", "a < b → a % b = a"],
  ["Nat.mod_eq_zero_of_dvd", "a ∣ b → b % a = 0"],
  ["Nat.dvd_of_mod_eq_zero", "n % k = 0 → k ∣ n"],
  ["Nat.dvd_iff_mod_eq_zero", "k ∣ n ↔ n % k = 0"],
  ["Nat.add_mod", "∀ (a b n : ℕ), (a + b) % n = (a % n + b % n) % n"],
  ["Nat.mul_mod", "∀ (a b n : ℕ), a * b % n = a % n * (b % n) % n"],
  ["Nat.pow_mod", "∀ (n m k : ℕ), n ^ m % k = (n % k) ^ m % k"],
  ["Nat.add_mul_mod_self_left", "∀ (a b c : ℕ), (a + b * c) % b = a % b"],
  ["Nat.add_mul_mod_self_right", "∀ (a b c : ℕ), (a + b * c) % c = a % c"],
  ["Nat.mul_mod_right", "∀ (n k : ℕ), n * k % n = 0"],
  ["Nat.mul_mod_left", "∀ (n k : ℕ), n * k % k = 0"],
  ["Nat.ModEq", "Nat.ModEq n a b ↔ a % n = b % n  (notation a ≡ b [MOD n])"],
  ["Nat.ModEq.add", "a ≡ b [MOD n] → c ≡ d [MOD n] → a + c ≡ b + d [MOD n]"],
  ["Nat.ModEq.mul", "a ≡ b [MOD n] → c ≡ d [MOD n] → a * c ≡ b * d [MOD n]"],
  ["Nat.ModEq.pow", "∀ (m : ℕ), a ≡ b [MOD n] → a ^ m ≡ b ^ m [MOD n]"],
  ["Nat.modEq_iff_dvd'", "c ≤ b → (c ≡ b [MOD n] ↔ n ∣ b - c)"],
  ["Nat.ModEq.symm", "a ≡ b [MOD n] → b ≡ a [MOD n]"],
  ["Nat.ModEq.trans", "a ≡ b [MOD n] → b ≡ c [MOD n] → a ≡ c [MOD n]"],
  ["Nat.le_induction", "P m → (∀ n ≥ m, P n → P (n + 1)) → ∀ n ≥ m, P n"],
  ["Nat.strong_induction_on", "∀ (n : ℕ), (∀ (n : ℕ), (∀ m < n, p m) → p n) → p n"],
  ["Nat.twoStepInduction", "P 0 → P 1 → (∀ (n : ℕ), P n → P (n + 1) → P (n + 2)) → ∀ (a : ℕ), P a"],
  ["Nat.find_spec", "(∃ n, p n) → p (Nat.find h)"],
  ["Nat.find_min'", "(∃ n, p n) → p m → Nat.find h ≤ m"],
  ["Nat.factorial_pos", "∀ (n : ℕ), 0 < n !"],
  ["Nat.factorial_succ", "∀ (n : ℕ), (n + 1)! = (n + 1) * n !"],
  ["Nat.factorial_le", "m ≤ n → m ! ≤ n !"],
  ["Nat.self_le_factorial", "∀ (n : ℕ), n ≤ n !"],
  ["Nat.choose_symm", "k ≤ n → n.choose (n - k) = n.choose k"],
  ["Nat.choose_two_right", "∀ (n : ℕ), n.choose 2 = n * (n - 1) / 2"],
  ["Nat.choose_one_right", "∀ (n : ℕ), n.choose 1 = n"],
  ["Nat.choose_self", "∀ (n : ℕ), n.choose n = 1"],
  ["Nat.choose_zero_right", "∀ (n : ℕ), n.choose 0 = 1"],
  ["Nat.choose_succ_succ", "∀ (n k : ℕ), (n + 1).choose (k + 1) = n.choose k + n.choose (k + 1)"],
  ["Nat.choose_eq_factorial_div_factorial", "k ≤ n → n.choose k = n ! / (k ! * (n - k)!)"],
  ["Nat.succ_mul_choose_eq", "∀ (n k : ℕ), (n + 1) * n.choose k = (n + 1).choose (k + 1) * (k + 1)"],
  ["Nat.choose_pos", "k ≤ n → 0 < n.choose k"],
  ["Nat.sum_range_choose", "∀ (n : ℕ), ∑ m ∈ Finset.range (n + 1), n.choose m = 2 ^ n"],
  ["Nat.cast_add", "∀ (m n : ℕ), ((m + n : ℕ) : R) = m + n"],
  ["Nat.cast_mul", "∀ (m n : ℕ), ((m * n : ℕ) : R) = m * n"],
  ["Nat.cast_pow", "∀ (n m : ℕ), ((n ^ m : ℕ) : R) = n ^ m"],
  ["Nat.cast_sub", "m ≤ n → ((n - m : ℕ) : R) = n - m"],
  ["Nat.cast_succ", "∀ (n : ℕ), ((n + 1 : ℕ) : R) = n + 1"],
  ["Nat.cast_le", "(m : α) ≤ n ↔ m ≤ n"],
  ["Nat.cast_lt", "(m : α) < n ↔ m < n"],
  ["Nat.cast_inj", "(m : R) = n ↔ m = n"],
  ["Nat.cast_nonneg", "∀ (n : ℕ), 0 ≤ (n : α)"],
  ["Nat.cast_pos", "0 < (n : α) ↔ 0 < n"],
  ["Nat.cast_ne_zero", "(n : R) ≠ 0 ↔ n ≠ 0"],
  ["Nat.cast_div_le", "((m / n : ℕ) : α) ≤ m / n"],
  ["Nat.floor_le", "0 ≤ a → ↑⌊a⌋₊ ≤ a"],
  ["Nat.lt_floor_add_one", "∀ (a : α), a < ⌊a⌋₊ + 1"],
  ["Nat.le_ceil", "∀ (a : α), a ≤ ⌈a⌉₊"],

  // ── Divisibility, gcd, primes ───────────────────────────────────────
  ["dvd_refl", "∀ (a : α), a ∣ a"],
  ["dvd_trans", "a ∣ b → b ∣ c → a ∣ c"],
  ["dvd_mul_right", "∀ (a b : α), a ∣ a * b"],
  ["dvd_mul_left", "∀ (a b : α), a ∣ b * a"],
  ["dvd_mul_of_dvd_left", "a ∣ b → ∀ (c : α), a ∣ b * c"],
  ["dvd_mul_of_dvd_right", "a ∣ b → ∀ (c : α), a ∣ c * b"],
  ["Dvd.dvd.mul_left", "a ∣ b → ∀ (c : α), a ∣ c * b"],
  ["Dvd.dvd.mul_right", "a ∣ b → ∀ (c : α), a ∣ b * c"],
  ["dvd_add", "a ∣ b → a ∣ c → a ∣ b + c"],
  ["dvd_sub", "a ∣ b → a ∣ c → a ∣ b - c"],
  ["dvd_sub'", "k ∣ m → k ∣ n → k ∣ m - n"],
  ["Nat.dvd_sub'", "k ∣ m → k ∣ n → k ∣ m - n"],
  ["dvd_pow", "a ∣ b → n ≠ 0 → a ∣ b ^ n"],
  ["dvd_pow_self", "∀ (a : α), n ≠ 0 → a ∣ a ^ n"],
  ["Dvd.dvd.pow", "a ∣ b → n ≠ 0 → a ∣ b ^ n"],
  ["dvd_add_right", "a ∣ b → (a ∣ b + c ↔ a ∣ c)"],
  ["dvd_add_left", "a ∣ c → (a ∣ b + c ↔ a ∣ b)"],
  ["Nat.dvd_add_right", "k ∣ m → (k ∣ m + n ↔ k ∣ n)"],
  ["Nat.dvd_antisymm", "m ∣ n → n ∣ m → m = n"],
  ["Nat.le_of_dvd", "0 < n → m ∣ n → m ≤ n"],
  ["Nat.eq_one_of_dvd_one", "n ∣ 1 → n = 1"],
  ["Nat.dvd_one", "n ∣ 1 ↔ n = 1"],
  ["Nat.dvd_sub_mod", "∀ (k : ℕ), n ∣ k - k % n"],
  ["Nat.dvd_gcd", "k ∣ m → k ∣ n → k ∣ m.gcd n"],
  ["Nat.gcd_dvd_left", "∀ (m n : ℕ), m.gcd n ∣ m"],
  ["Nat.gcd_dvd_right", "∀ (m n : ℕ), m.gcd n ∣ n"],
  ["Nat.gcd_comm", "∀ (m n : ℕ), m.gcd n = n.gcd m"],
  ["Nat.gcd_mul_lcm", "∀ (m n : ℕ), m.gcd n * m.lcm n = m * n"],
  ["Nat.gcd_pos_of_pos_left", "∀ (n : ℕ), 0 < m → 0 < m.gcd n"],
  ["Nat.gcd_eq_gcd_ab", "∀ (x y : ℕ), ↑(x.gcd y) = ↑x * x.gcdA y + ↑y * x.gcdB y"],
  ["Nat.Coprime", "Nat.Coprime m n ↔ m.gcd n = 1"],
  ["Nat.Coprime.dvd_of_dvd_mul_left", "k.Coprime n → k ∣ m * n → k ∣ m"],
  ["Nat.Coprime.dvd_of_dvd_mul_right", "k.Coprime m → k ∣ m * n → k ∣ n"],
  ["Nat.Coprime.mul_dvd_of_dvd_of_dvd", "k.Coprime n → k ∣ m → n ∣ m → k * n ∣ m"],
  ["Nat.Coprime.gcd_eq_one", "m.Coprime n → m.gcd n = 1"],
  ["Nat.coprime_primes", "p.Prime → q.Prime → (p.Coprime q ↔ p ≠ q)"],
  ["Nat.Coprime.symm", "n.Coprime m → m.Coprime n"],
  ["Nat.coprime_comm", "n.Coprime m ↔ m.Coprime n"],
  ["Nat.Prime", "Nat.Prime p — p ≥ 2 and its only divisors are 1 and p"],
  ["Nat.Prime.two_le", "p.Prime → 2 ≤ p"],
  ["Nat.Prime.one_lt", "p.Prime → 1 < p"],
  ["Nat.Prime.pos", "p.Prime → 0 < p"],
  ["Nat.Prime.ne_zero", "p.Prime → p ≠ 0"],
  ["Nat.Prime.ne_one", "p.Prime → p ≠ 1"],
  ["Nat.prime_two", "Nat.Prime 2"],
  ["Nat.prime_three", "Nat.Prime 3"],
  ["Nat.prime_five", "Nat.Prime 5"],
  ["Nat.prime_def_lt", "p.Prime ↔ 2 ≤ p ∧ ∀ m < p, m ∣ p → m = 1"],
  ["Nat.prime_def_lt''", "p.Prime ↔ 2 ≤ p ∧ ∀ (m : ℕ), m ∣ p → m = 1 ∨ m = p"],
  ["Nat.Prime.eq_one_or_self_of_dvd", "p.Prime → ∀ (a : ℕ), a ∣ p → a = 1 ∨ a = p"],
  ["Nat.Prime.dvd_mul", "p.Prime → (p ∣ m * n ↔ p ∣ m ∨ p ∣ n)"],
  ["Nat.Prime.dvd_of_dvd_pow", "p.Prime → p ∣ m ^ n → p ∣ m"],
  ["Nat.Prime.dvd_factorial", "p.Prime → (p ∣ n ! ↔ p ≤ n)"],
  ["Nat.Prime.not_dvd_one", "p.Prime → ¬p ∣ 1"],
  ["Nat.Prime.eq_two_or_odd", "p.Prime → p = 2 ∨ p % 2 = 1"],
  ["Nat.Prime.eq_two_or_odd'", "p.Prime → p = 2 ∨ Odd p"],
  ["Nat.Prime.mod_two_eq_one_iff_ne_two", "p.Prime → (p % 2 = 1 ↔ p ≠ 2)"],
  ["Nat.Prime.five_le_of_ne_two_of_ne_three", "p.Prime → p ≠ 2 → p ≠ 3 → 5 ≤ p"],
  ["Nat.Prime.coprime_iff_not_dvd", "p.Prime → (p.Coprime n ↔ ¬p ∣ n)"],
  ["Nat.prime_dvd_prime_iff_eq", "p.Prime → q.Prime → (p ∣ q ↔ p = q)"],
  ["Nat.exists_prime_and_dvd", "n ≠ 1 → ∃ p, p.Prime ∧ p ∣ n"],
  ["Nat.exists_infinite_primes", "∀ (n : ℕ), ∃ p, n ≤ p ∧ p.Prime"],
  ["Nat.minFac_prime", "n ≠ 1 → n.minFac.Prime"],
  ["Nat.minFac_dvd", "∀ (n : ℕ), n.minFac ∣ n"],
  ["Nat.Prime.factorization_pos_of_dvd", "p.Prime → n ≠ 0 → p ∣ n → 0 < n.factorization p"],
  ["Nat.sq_sub_sq'", "∀ (a b : ℕ), a ^ 2 - b ^ 2 = (a + b) * (a - b)"],

  // ── Parity ──────────────────────────────────────────────────────────
  ["Nat.even_or_odd", "∀ (n : ℕ), Even n ∨ Odd n"],
  ["Nat.even_or_odd'", "∀ (n : ℕ), ∃ k, n = 2 * k ∨ n = 2 * k + 1"],
  ["Nat.even_iff", "Even n ↔ n % 2 = 0"],
  ["Nat.odd_iff", "Odd n ↔ n % 2 = 1"],
  ["Nat.not_even_iff_odd", "¬Even n ↔ Odd n"],
  ["Nat.not_odd_iff_even", "¬Odd n ↔ Even n"],
  ["Nat.even_add_one", "Even (n + 1) ↔ ¬Even n"],
  ["Nat.even_add", "Even (m + n) ↔ (Even m ↔ Even n)"],
  ["Nat.even_sub", "n ≤ m → (Even (m - n) ↔ (Even m ↔ Even n))"],
  ["Nat.even_mul", "Even (m * n) ↔ Even m ∨ Even n"],
  ["Nat.odd_mul", "Odd (m * n) ↔ Odd m ∧ Odd n"],
  ["Nat.even_pow", "Even (m ^ n) ↔ Even m ∧ n ≠ 0"],
  ["Nat.odd_add", "Odd (m + n) ↔ (Odd m ↔ Even n)"],
  ["Nat.even_mul_succ_self", "∀ (n : ℕ), Even (n * (n + 1))"],
  ["Nat.even_mul_self_pred", "∀ (n : ℕ), Even (n * (n - 1))"],
  ["even_iff_two_dvd", "Even a ↔ 2 ∣ a"],
  ["odd_iff_exists_bit1", "Odd a ↔ ∃ b, a = 2 * b + 1"],
  ["even_two_mul", "∀ (m : α), Even (2 * m)"],
  ["odd_two_mul_add_one", "∀ (m : α), Odd (2 * m + 1)"],
  ["Even.add_odd", "Even m → Odd n → Odd (m + n)"],
  ["Odd.add_odd", "Odd m → Odd n → Even (m + n)"],
  ["Even.add", "Even m → Even n → Even (m + n)"],
  ["Even.mul_right", "Even m → ∀ (n : α), Even (m * n)"],
  ["Even.mul_left", "Even m → ∀ (n : α), Even (n * m)"],
  ["Odd.mul", "Odd m → Odd n → Odd (m * n)"],
  ["Even.pow", "Even m → n ≠ 0 → Even (m ^ n)"],
  ["Odd.pow", "Odd m → Odd (m ^ n)"],
  ["Even.neg_pow", "Even n → ∀ (a : α), (-a) ^ n = a ^ n"],
  ["Odd.neg_pow", "Odd n → ∀ (a : α), (-a) ^ n = -a ^ n"],
  ["Even.pow_nonneg", "Even n → ∀ (a : α), 0 ≤ a ^ n"],
  ["Odd.pow_nonneg_iff", "Odd n → (0 ≤ a ^ n ↔ 0 ≤ a)"],
  ["Int.even_or_odd", "∀ (n : ℤ), Even n ∨ Odd n"],
  ["Int.even_iff", "Even n ↔ n % 2 = 0"],
  ["Int.odd_iff", "Odd n ↔ n % 2 = 1"],
  ["Int.not_even_iff_odd", "¬Even n ↔ Odd n"],
  ["Int.even_add", "Even (m + n) ↔ (Even m ↔ Even n)"],
  ["Int.even_mul", "Even (m * n) ↔ Even m ∨ Even n"],
  ["Int.even_pow", "Even (m ^ n) ↔ Even m ∧ n ≠ 0"],
  ["Int.emod_two_eq_zero_or_one", "∀ (n : ℤ), n % 2 = 0 ∨ n % 2 = 1"],
  ["Int.even_add_one", "Even (n + 1) ↔ ¬Even n"],

  // ── ℤ arithmetic and modular arithmetic ─────────────────────────────
  ["Int.emod_emod_of_dvd", "∀ (n : ℤ), m ∣ k → n % k % m = n % m"],
  ["Int.emod_nonneg", "∀ (a : ℤ), b ≠ 0 → 0 ≤ a % b"],
  ["Int.emod_lt_of_pos", "∀ (a : ℤ), 0 < b → a % b < b"],
  ["Int.ediv_add_emod", "∀ (a b : ℤ), b * (a / b) + a % b = a"],
  ["Int.emod_add_ediv", "∀ (a b : ℤ), a % b + b * (a / b) = a"],
  ["Int.add_mul_emod_self", "∀ {a b c : ℤ}, (a + b * c) % c = a % c"],
  ["Int.add_mul_emod_self_left", "∀ (a b c : ℤ), (a + b * c) % b = a % b"],
  ["Int.add_emod", "∀ (a b n : ℤ), (a + b) % n = (a % n + b % n) % n"],
  ["Int.mul_emod", "∀ (a b n : ℤ), a * b % n = a % n * (b % n) % n"],
  ["Int.sub_emod", "∀ (a b n : ℤ), (a - b) % n = (a % n - b % n) % n"],
  ["Int.emod_eq_of_lt", "0 ≤ a → a < b → a % b = a"],
  ["Int.emod_eq_zero_of_dvd", "a ∣ b → b % a = 0"],
  ["Int.dvd_of_emod_eq_zero", "b % a = 0 → a ∣ b"],
  ["Int.ModEq", "Int.ModEq n a b ↔ a % n = b % n  (notation a ≡ b [ZMOD n])"],
  ["Int.ModEq.add", "a ≡ b [ZMOD n] → c ≡ d [ZMOD n] → a + c ≡ b + d [ZMOD n]"],
  ["Int.ModEq.mul", "a ≡ b [ZMOD n] → c ≡ d [ZMOD n] → a * c ≡ b * d [ZMOD n]"],
  ["Int.ModEq.pow", "∀ (m : ℕ), a ≡ b [ZMOD n] → a ^ m ≡ b ^ m [ZMOD n]"],
  ["Int.modEq_iff_dvd", "a ≡ b [ZMOD n] ↔ n ∣ b - a"],
  ["Int.le_of_dvd", "0 < b → a ∣ b → a ≤ b"],
  ["Int.eq_one_of_dvd_one", "0 ≤ a → a ∣ 1 → a = 1"],
  ["Int.natAbs_dvd_natAbs", "a.natAbs ∣ b.natAbs ↔ a ∣ b"],
  ["Int.natAbs_mul", "∀ (a b : ℤ), (a * b).natAbs = a.natAbs * b.natAbs"],
  ["Int.natAbs_pow", "∀ (n : ℤ) (k : ℕ), (n ^ k).natAbs = n.natAbs ^ k"],
  ["Int.natAbs_eq_zero", "a.natAbs = 0 ↔ a = 0"],
  ["Int.natAbs_of_nonneg", "0 ≤ a → ↑a.natAbs = a"],
  ["Int.abs_eq_natAbs", "∀ (a : ℤ), |a| = ↑a.natAbs"],
  ["Int.natAbs_dvd", "↑a.natAbs ∣ b ↔ a ∣ b"],
  ["Int.dvd_natAbs", "a ∣ ↑b.natAbs ↔ a ∣ b"],
  ["Int.toNat_of_nonneg", "0 ≤ a → ↑a.toNat = a"],
  ["Int.lt_iff_add_one_le", "a < b ↔ a + 1 ≤ b"],
  ["Int.add_one_le_iff", "a + 1 ≤ b ↔ a < b"],
  ["Int.lt_add_one_iff", "a < b + 1 ↔ a ≤ b"],
  ["Int.sub_one_lt_iff", "a - 1 < b ↔ a ≤ b"],
  ["Int.natCast_dvd_natCast", "(↑m ∣ ↑n) ↔ m ∣ n"],
  ["Int.natCast_pos", "0 < (n : ℤ) ↔ 0 < n"],
  ["Int.cast_add", "∀ (m n : ℤ), ((m + n : ℤ) : R) = m + n"],
  ["Int.cast_mul", "∀ (m n : ℤ), ((m * n : ℤ) : R) = m * n"],
  ["Int.cast_pow", "∀ (n : ℤ) (m : ℕ), ((n ^ m : ℤ) : R) = n ^ m"],
  ["Int.cast_le", "(m : R) ≤ n ↔ m ≤ n"],
  ["Int.cast_lt", "(m : R) < n ↔ m < n"],
  ["Int.cast_inj", "(m : R) = n ↔ m = n"],
  ["Int.cast_abs", "∀ (a : ℤ), ((|a| : ℤ) : R) = |a|"],
  ["Int.eq_one_or_neg_one_of_mul_eq_one", "z * w = 1 → z = 1 ∨ z = -1"],
  ["Int.isUnit_iff", "IsUnit n ↔ n = 1 ∨ n = -1"],
  ["Int.floor_le", "∀ (r : α), ↑⌊r⌋ ≤ r"],
  ["Int.lt_floor_add_one", "∀ (r : α), r < ↑⌊r⌋ + 1"],
  ["Int.floor_eq_iff", "↑z = ⌊r⌋ ↔ ↑z ≤ r ∧ r < ↑z + 1"],
  ["Int.le_ceil", "∀ (r : α), r ≤ ↑⌈r⌉"],
  ["Int.fract_nonneg", "∀ (r : α), 0 ≤ Int.fract r"],
  ["Int.fract_lt_one", "∀ (r : α), Int.fract r < 1"],
  ["Int.floor_add_fract", "∀ (r : α), ↑⌊r⌋ + Int.fract r = r"],

  // ── Finite sums, products, counting ─────────────────────────────────
  ["Finset.sum_range_succ", "∀ (f : ℕ → M) (n : ℕ), ∑ x ∈ Finset.range (n + 1), f x = ∑ x ∈ Finset.range n, f x + f n"],
  ["Finset.sum_range_succ'", "∀ (f : ℕ → M) (n : ℕ), ∑ i ∈ Finset.range (n + 1), f i = ∑ i ∈ Finset.range n, f (i + 1) + f 0"],
  ["Finset.sum_range_zero", "∀ (f : ℕ → M), ∑ k ∈ Finset.range 0, f k = 0"],
  ["Finset.sum_range_one", "∀ (f : ℕ → M), ∑ k ∈ Finset.range 1, f k = f 0"],
  ["Finset.prod_range_succ", "∀ (f : ℕ → M) (n : ℕ), ∏ x ∈ Finset.range (n + 1), f x = (∏ x ∈ Finset.range n, f x) * f n"],
  ["Finset.prod_range_zero", "∀ (f : ℕ → M), ∏ k ∈ Finset.range 0, f k = 1"],
  ["Finset.sum_range_id_mul_two", "∀ (n : ℕ), (∑ i ∈ Finset.range n, i) * 2 = n * (n - 1)"],
  ["Finset.sum_range_id", "∀ (n : ℕ), ∑ i ∈ Finset.range n, i = n * (n - 1) / 2"],
  ["geom_sum_eq", "x ≠ 1 → ∀ (n : ℕ), ∑ i ∈ Finset.range n, x ^ i = (x ^ n - 1) / (x - 1)"],
  ["geom_sum_mul", "∀ (x : α) (n : ℕ), (∑ i ∈ Finset.range n, x ^ i) * (x - 1) = x ^ n - 1"],
  ["Finset.sum_const", "∀ (b : M), ∑ _x ∈ s, b = s.card • b"],
  ["Finset.sum_const_nat", "(∀ x ∈ s, f x = m) → ∑ x ∈ s, f x = s.card * m"],
  ["Finset.prod_const", "∀ (b : M), ∏ _x ∈ s, b = b ^ s.card"],
  ["Finset.card_range", "∀ (n : ℕ), (Finset.range n).card = n"],
  ["Finset.card_fin", "∀ (n : ℕ), Finset.univ.card = n  (univ : Finset (Fin n))"],
  ["Fintype.card_fin", "∀ (n : ℕ), Fintype.card (Fin n) = n"],
  ["Finset.card_eq_sum_ones", "∀ (s : Finset α), s.card = ∑ _x ∈ s, 1"],
  ["Finset.sum_le_sum", "(∀ i ∈ s, f i ≤ g i) → s.sum f ≤ s.sum g"],
  ["Finset.sum_lt_sum", "(∀ i ∈ s, f i ≤ g i) → (∃ i ∈ s, f i < g i) → s.sum f < s.sum g"],
  ["Finset.sum_lt_sum_of_nonempty", "s.Nonempty → (∀ i ∈ s, f i < g i) → s.sum f < s.sum g"],
  ["Finset.sum_nonneg", "(∀ i ∈ s, 0 ≤ f i) → 0 ≤ ∑ i ∈ s, f i"],
  ["Finset.sum_pos", "(∀ i ∈ s, 0 < f i) → s.Nonempty → 0 < ∑ i ∈ s, f i"],
  ["Finset.prod_pos", "(∀ i ∈ s, 0 < f i) → 0 < ∏ i ∈ s, f i"],
  ["Finset.prod_nonneg", "(∀ i ∈ s, 0 ≤ f i) → 0 ≤ ∏ i ∈ s, f i"],
  ["Finset.prod_le_prod", "(∀ i ∈ s, 0 ≤ f i) → (∀ i ∈ s, f i ≤ g i) → s.prod f ≤ s.prod g"],
  ["Finset.sum_le_card_nsmul", "∀ (s : Finset ι) (f : ι → M) (n : M), (∀ x ∈ s, f x ≤ n) → s.sum f ≤ s.card • n"],
  ["Finset.card_nsmul_le_sum", "∀ (s : Finset ι) (f : ι → M) (n : M), (∀ x ∈ s, n ≤ f x) → s.card • n ≤ s.sum f"],
  ["Finset.exists_le_of_sum_le", "s.Nonempty → ∑ i ∈ s, f i ≤ ∑ i ∈ s, g i → ∃ i ∈ s, f i ≤ g i"],
  ["Finset.exists_lt_of_sum_lt", "∑ i ∈ s, f i < ∑ i ∈ s, g i → ∃ i ∈ s, f i < g i"],
  ["Finset.single_le_sum", "(∀ i ∈ s, 0 ≤ f i) → a ∈ s → f a ≤ ∑ x ∈ s, f x"],
  ["Finset.sum_add_distrib", "∑ i ∈ s, (f i + g i) = ∑ i ∈ s, f i + ∑ i ∈ s, g i"],
  ["Finset.sum_sub_distrib", "∑ i ∈ s, (f i - g i) = ∑ i ∈ s, f i - ∑ i ∈ s, g i"],
  ["Finset.sum_neg_distrib", "∑ i ∈ s, -f i = -∑ i ∈ s, f i"],
  ["Finset.mul_sum", "∀ (s : Finset ι) (f : ι → α) (b : α), b * ∑ i ∈ s, f i = ∑ i ∈ s, b * f i"],
  ["Finset.sum_mul", "∀ (s : Finset ι) (f : ι → α) (b : α), (∑ i ∈ s, f i) * b = ∑ i ∈ s, f i * b"],
  ["Finset.sum_div", "∀ (s : Finset ι) (f : ι → α) (b : α), (∑ i ∈ s, f i) / b = ∑ i ∈ s, f i / b"],
  ["Finset.sum_comm", "∑ x ∈ s, ∑ y ∈ t, f x y = ∑ y ∈ t, ∑ x ∈ s, f x y"],
  ["Finset.sum_congr", "s₁ = s₂ → (∀ x ∈ s₂, f x = g x) → s₁.sum f = s₂.sum g"],
  ["Finset.prod_congr", "s₁ = s₂ → (∀ x ∈ s₂, f x = g x) → s₁.prod f = s₂.prod g"],
  ["Finset.sum_ite_eq", "∑ x ∈ s, (if a = x then b x else 0) = if a ∈ s then b a else 0"],
  ["Finset.sum_filter", "∑ a ∈ s.filter p, f a = ∑ a ∈ s, if p a then f a else 0"],
  ["Finset.sum_range_reflect", "∀ (f : ℕ → M) (n : ℕ), ∑ j ∈ Finset.range n, f (n - 1 - j) = ∑ j ∈ Finset.range n, f j"],
  ["Finset.mem_range", "m ∈ Finset.range n ↔ m < n"],
  ["Finset.mem_Icc", "a ∈ Finset.Icc b c ↔ b ≤ a ∧ a ≤ c"],
  ["Finset.mem_Ico", "a ∈ Finset.Ico b c ↔ b ≤ a ∧ a < c"],
  ["Finset.mem_filter", "a ∈ s.filter p ↔ a ∈ s ∧ p a"],
  ["Finset.mem_image", "b ∈ s.image f ↔ ∃ a ∈ s, f a = b"],
  ["Finset.mem_univ", "∀ (x : α), x ∈ Finset.univ"],
  ["Finset.mem_insert", "a ∈ insert b s ↔ a = b ∨ a ∈ s"],
  ["Finset.mem_union", "a ∈ s ∪ t ↔ a ∈ s ∨ a ∈ t"],
  ["Finset.mem_inter", "a ∈ s ∩ t ↔ a ∈ s ∧ a ∈ t"],
  ["Finset.mem_sdiff", "a ∈ s \\ t ↔ a ∈ s ∧ a ∉ t"],
  ["Finset.card_pos", "0 < s.card ↔ s.Nonempty"],
  ["Finset.card_eq_zero", "s.card = 0 ↔ s = ∅"],
  ["Finset.card_le_card", "s ⊆ t → s.card ≤ t.card"],
  ["Finset.card_lt_card", "s ⊂ t → s.card < t.card"],
  ["Finset.card_insert_of_not_mem", "a ∉ s → (insert a s).card = s.card + 1"],
  ["Finset.card_union_add_card_inter", "∀ (s t : Finset α), (s ∪ t).card + (s ∩ t).card = s.card + t.card"],
  ["Finset.card_union_le", "∀ (s t : Finset α), (s ∪ t).card ≤ s.card + t.card"],
  ["Finset.card_sdiff", "s ⊆ t → (t \\ s).card = t.card - s.card"],
  ["Finset.card_image_le", "(s.image f).card ≤ s.card"],
  ["Finset.card_image_of_injective", "∀ (s : Finset α), Function.Injective f → (s.image f).card = s.card"],
  ["Finset.card_filter_le", "∀ (s : Finset α) (p : α → Prop), (s.filter p).card ≤ s.card"],
  ["Finset.filter_card_add_filter_neg_card_eq_card", "∀ (p : α → Prop), (s.filter p).card + (s.filter (fun a => ¬p a)).card = s.card"],
  ["Nat.card_Icc", "∀ (a b : ℕ), (Finset.Icc a b).card = b + 1 - a"],
  ["Finset.exists_ne_map_eq_of_card_lt_of_maps_to", "t.card < s.card → (∀ a ∈ s, f a ∈ t) → ∃ x ∈ s, ∃ y ∈ s, x ≠ y ∧ f x = f y"],
  ["Fintype.exists_ne_map_eq_of_card_lt", "∀ (f : α → β), Fintype.card β < Fintype.card α → ∃ x y, x ≠ y ∧ f x = f y"],
  ["Finset.exists_max_image", "∀ (s : Finset β) (f : β → α), s.Nonempty → ∃ x ∈ s, ∀ x' ∈ s, f x' ≤ f x"],
  ["Finset.exists_min_image", "∀ (s : Finset β) (f : β → α), s.Nonempty → ∃ x ∈ s, ∀ x' ∈ s, f x ≤ f x'"],
  ["Finset.sum_boole", "∑ i ∈ s, (if p i then 1 else 0) = (s.filter p).card"],
  ["Finset.card_eq_of_equiv", "s ≃ t → s.card = t.card"],
  ["Finset.induction_on", "p ∅ → (∀ a s, a ∉ s → p s → p (insert a s)) → p s"],
  ["Finset.Nonempty", "s.Nonempty ↔ ∃ x, x ∈ s"],
  ["Finset.nonempty_of_ne_empty", "s ≠ ∅ → s.Nonempty"],
  ["Finset.nonempty_range_iff", "(Finset.range n).Nonempty ↔ n ≠ 0"],
  ["Finset.eq_empty_iff_forall_not_mem", "s = ∅ ↔ ∀ (x : α), x ∉ s"],
  ["Finset.subset_iff", "s ⊆ t ↔ ∀ ⦃x : α⦄, x ∈ s → x ∈ t"],

  // ── Sets, functions, logic ──────────────────────────────────────────
  ["Set.mem_setOf_eq", "(a ∈ {x | p x}) = p a"],
  ["Set.mem_def", "a ∈ s ↔ s a"],
  ["Set.subset_def", "(s ⊆ t) = ∀ x ∈ s, x ∈ t"],
  ["Set.ext", "(∀ (x : α), x ∈ s ↔ x ∈ t) → s = t"],
  ["Set.mem_inter_iff", "∀ (x : α) (a b : Set α), x ∈ a ∩ b ↔ x ∈ a ∧ x ∈ b"],
  ["Set.mem_union", "∀ (x : α) (a b : Set α), x ∈ a ∪ b ↔ x ∈ a ∨ x ∈ b"],
  ["Set.mem_Icc", "a ∈ Set.Icc b c ↔ b ≤ a ∧ a ≤ c"],
  ["Set.mem_Ioo", "a ∈ Set.Ioo b c ↔ b < a ∧ a < c"],
  ["Set.mem_Ici", "a ∈ Set.Ici b ↔ b ≤ a"],
  ["Set.mem_Ioi", "a ∈ Set.Ioi b ↔ b < a"],
  ["Set.Subset.antisymm", "a ⊆ b → b ⊆ a → a = b"],
  ["Function.Injective", "Function.Injective f ↔ ∀ a₁ a₂, f a₁ = f a₂ → a₁ = a₂"],
  ["Function.Surjective", "Function.Surjective f ↔ ∀ b, ∃ a, f a = b"],
  ["Function.Injective.eq_iff", "Function.Injective f → (f a = f b ↔ a = b)"],
  ["StrictMono.injective", "StrictMono f → Function.Injective f"],
  ["StrictMono.lt_iff_lt", "StrictMono f → (f a < f b ↔ a < b)"],
  ["StrictMono.le_iff_le", "StrictMono f → (f a ≤ f b ↔ a ≤ b)"],
  ["Monotone", "Monotone f ↔ ∀ a b, a ≤ b → f a ≤ f b"],
  ["not_not", "¬¬a ↔ a"],
  ["not_forall", "(¬∀ x, p x) ↔ ∃ x, ¬p x"],
  ["not_exists", "(¬∃ x, p x) ↔ ∀ x, ¬p x"],
  ["not_and_or", "¬(a ∧ b) ↔ ¬a ∨ ¬b"],
  ["not_or", "¬(a ∨ b) ↔ ¬a ∧ ¬b"],
  ["not_imp", "¬(a → b) ↔ a ∧ ¬b"],
  ["Classical.byContradiction", "(¬p → False) → p"],
  ["Classical.em", "∀ (p : Prop), p ∨ ¬p"],
  ["and_comm", "a ∧ b ↔ b ∧ a"],
  ["or_comm", "a ∨ b ↔ b ∨ a"],
  ["Or.resolve_left", "a ∨ b → ¬a → b"],
  ["Or.resolve_right", "a ∨ b → ¬b → a"],
  ["Exists.intro", "∀ (w : α), p w → ∃ x, p x"],
  ["exists_prop", "(∃ (_ : a), b) ↔ a ∧ b"],
  ["forall_and", "(∀ x, p x ∧ q x) ↔ (∀ x, p x) ∧ ∀ x, q x"],
  ["eq_comm", "a = b ↔ b = a"],
  ["ne_comm", "a ≠ b ↔ b ≠ a"],
  ["ne_eq", "(a ≠ b) = ¬a = b"],
  ["Eq.symm", "a = b → b = a"],
  ["Eq.trans", "a = b → b = c → a = c"],
  ["congrArg", "∀ (f : α → β), a₁ = a₂ → f a₁ = f a₂"],
  ["funext", "(∀ x, f x = g x) → f = g"],
  ["Iff.mp", "(a ↔ b) → a → b"],
  ["Iff.mpr", "(a ↔ b) → b → a"],
  ["absurd", "a → ¬a → b"],
  ["False.elim", "False → C"],

  // ── Complex numbers ─────────────────────────────────────────────────
  ["Complex.ext_iff", "z = w ↔ z.re = w.re ∧ z.im = w.im"],
  ["Complex.I_sq", "Complex.I ^ 2 = -1"],
  ["Complex.I_mul_I", "Complex.I * Complex.I = -1"],
  ["Complex.add_re", "∀ (z w : ℂ), (z + w).re = z.re + w.re"],
  ["Complex.add_im", "∀ (z w : ℂ), (z + w).im = z.im + w.im"],
  ["Complex.mul_re", "∀ (z w : ℂ), (z * w).re = z.re * w.re - z.im * w.im"],
  ["Complex.mul_im", "∀ (z w : ℂ), (z * w).im = z.re * w.im + z.im * w.re"],
  ["Complex.normSq_apply", "∀ (z : ℂ), Complex.normSq z = z.re * z.re + z.im * z.im"],
  ["Complex.normSq_nonneg", "∀ (z : ℂ), 0 ≤ Complex.normSq z"],
  ["Complex.conj_re", "∀ (z : ℂ), ((starRingEnd ℂ) z).re = z.re"],
  ["Complex.conj_im", "∀ (z : ℂ), ((starRingEnd ℂ) z).im = -z.im"],
  ["Complex.ofReal_re", "∀ (r : ℝ), (↑r : ℂ).re = r"],
  ["Complex.ofReal_im", "∀ (r : ℝ), (↑r : ℂ).im = 0"],
  ["Complex.exp_add", "∀ (x y : ℂ), Complex.exp (x + y) = Complex.exp x * Complex.exp y"],
  ["Complex.exp_mul_I", "∀ (x : ℂ), Complex.exp (x * Complex.I) = Complex.cos x + Complex.sin x * Complex.I"],

  // ── Polynomials, rationals, misc ────────────────────────────────────
  ["Rat.num_div_den", "∀ (r : ℚ), ↑r.num / ↑r.den = r"],
  ["Rat.den_pos", "∀ (r : ℚ), 0 < r.den"],
  ["Rat.reduced", "∀ (r : ℚ), r.num.natAbs.Coprime r.den"],
  ["Irrational", "Irrational x ↔ x ∉ Set.range Rat.cast"],
  ["irrational_sqrt_two", "Irrational √2"],
  ["Nat.Prime.irrational_sqrt", "p.Prime → Irrational √↑p"],
  ["Irrational.ne_nat", "Irrational x → ∀ (m : ℕ), x ≠ ↑m"],
  ["Irrational.add_rat", "∀ (q : ℚ), Irrational x → Irrational (x + ↑q)"],
  ["Polynomial.eval_add", "∀ (p q : R[X]) (x : R), Polynomial.eval x (p + q) = Polynomial.eval x p + Polynomial.eval x q"],
  ["Polynomial.degree_add_le", "∀ (p q : R[X]), (p + q).degree ≤ max p.degree q.degree"],
  ["Polynomial.card_roots'", "∀ (p : R[X]), Multiset.card p.roots ≤ p.natDegree"],
  ["Real.sqrt_two_mul_self", "√2 * √2 = 2"],
  ["Real.sqrt_eq_iff_sq_eq", "0 ≤ x → 0 ≤ y → (√x = y ↔ y ^ 2 = x)"],
  ["Nat.sqrt_le'", "∀ (n : ℕ), n.sqrt ^ 2 ≤ n"],
  ["Nat.lt_succ_sqrt'", "∀ (n : ℕ), n < (n.sqrt + 1) ^ 2"],
  ["Nat.sqrt_eq'", "∀ (n : ℕ), (n ^ 2).sqrt = n"],
  ["Nat.digits_add_two_add_one", "∀ (b n : ℕ), (b + 2).digits (n + 1) = ((n + 1) % (b + 2)) :: (b + 2).digits ((n + 1) / (b + 2))"],
  ["Nat.digits_def'", "1 < b → 0 < n → b.digits n = (n % b) :: b.digits (n / b)"],
  ["Nat.ofDigits_digits", "∀ (b n : ℕ), Nat.ofDigits b (b.digits n) = n"],
  ["Nat.modEq_three_digits_sum", "∀ (n : ℕ), n ≡ (Nat.digits 10 n).sum [MOD 3]"],
  ["Nat.modEq_nine_digits_sum", "∀ (n : ℕ), n ≡ (Nat.digits 10 n).sum [MOD 9]"],
  ["Nat.three_dvd_iff", "3 ∣ n ↔ 3 ∣ (Nat.digits 10 n).sum"],
  ["Nat.nine_dvd_iff", "9 ∣ n ↔ 9 ∣ (Nat.digits 10 n).sum"],
  ["ZMod.natCast_self_eq_zero", "(n : ZMod n) = 0"],
  ["ZMod.natCast_zmod_eq_zero_iff_dvd", "(↑a : ZMod b) = 0 ↔ b ∣ a"],
  ["ZMod.intCast_zmod_eq_zero_iff_dvd", "(↑a : ZMod b) = 0 ↔ ↑b ∣ a"],
  ["ZMod.pow_card_sub_one_eq_one", "(a : ZMod p) ≠ 0 → a ^ (p - 1) = 1  (Fermat's little theorem)"],
  ["Nat.ModEq.pow_totient", "x.Coprime n → x ^ φ n ≡ 1 [MOD n]  (Euler's theorem)"],
  ["Int.ModEq.pow_card_sub_one_eq_one", "p.Prime → IsCoprime n ↑p → n ^ (p - 1) ≡ 1 [ZMOD ↑p]  (Fermat's little theorem)"],
  ["Nat.Prime.dvd_choose_self", "p.Prime → k ≠ 0 → k < p → p ∣ p.choose k"],
  ["Nat.totient_prime", "p.Prime → φ p = p - 1"],
  ["Int.gcd_eq_gcd_ab", "∀ (x y : ℤ), ↑(x.gcd y) = x * x.gcdA y + y * x.gcdB y  (Bézout)"],
  ["Nat.exists_mul_emod_eq_one_of_coprime", "n.Coprime k → 1 < k → ∃ m, n * m % k = 1"],
  ["Nat.chineseRemainder", "n.Coprime m → ∀ (a b : ℕ), { k // k ≡ a [MOD n] ∧ k ≡ b [MOD m] }"],
  ["Finset.sum_range_succ_comm", "∀ (f : ℕ → M) (n : ℕ), ∑ x ∈ Finset.range (n + 1), f x = f n + ∑ x ∈ Finset.range n, f x"],
  ["Finset.prod_range_succ_comm", "∀ (f : ℕ → M) (n : ℕ), ∏ x ∈ Finset.range (n + 1), f x = f n * ∏ x ∈ Finset.range n, f x"],
  ["Finset.card_eq_two", "s.card = 2 ↔ ∃ x y, x ≠ y ∧ s = {x, y}"],
  ["Finset.card_eq_one", "s.card = 1 ↔ ∃ a, s = {a}"],
  ["Finset.card_singleton", "∀ (a : α), ({a} : Finset α).card = 1"],
  ["Finset.card_pair", "a ≠ b → ({a, b} : Finset α).card = 2"],
  ["Finset.sum_pair", "a ≠ b → ∑ x ∈ {a, b}, f x = f a + f b"],
  ["Finset.prod_pair", "a ≠ b → ∏ x ∈ {a, b}, f x = f a * f b"],
  ["Finset.sum_singleton", "∀ (f : α → M) (a : α), ∑ x ∈ {a}, f x = f a"],
  ["Finset.sum_insert", "a ∉ s → ∑ x ∈ insert a s, f x = f a + ∑ x ∈ s, f x"],
  ["Finset.sum_erase", "f a = 0 → ∑ x ∈ s.erase a, f x = ∑ x ∈ s, f x"],
  ["Finset.sum_image", "(∀ x ∈ s, ∀ y ∈ s, g x = g y → x = y) → ∑ x ∈ s.image g, f x = ∑ x ∈ s, f (g x)"],
  ["Finset.sum_bij", "(bijection between index sets with matching terms) → s.sum f = t.sum g"],
  ["Finset.sum_equiv", "(e : ι ≃ κ) → (∀ i, i ∈ s ↔ e i ∈ t) → (∀ i ∈ s, f i = g (e i)) → s.sum f = t.sum g"],
  ["Finset.sum_fiberwise", "∑ j ∈ t, ∑ i ∈ s.filter (fun i => g i = j), f i = ∑ i ∈ s, f i  (when g maps s into t)"],
  ["Finset.sum_product", "∑ x ∈ s ×ˢ t, f x = ∑ x ∈ s, ∑ y ∈ t, f (x, y)"],
  ["Finset.sum_sigma", "∑ x ∈ s.sigma t, f x = ∑ a ∈ s, ∑ s ∈ t a, f ⟨a, s⟩"],
  ["Finset.sum_range", "∑ i ∈ Finset.range n, f i = ∑ i : Fin n, f ↑i"],
  ["Fin.sum_univ_succ", "∀ (f : Fin (n + 1) → M), ∑ i, f i = f 0 + ∑ i : Fin n, f i.succ"],
  ["Fin.sum_univ_castSucc", "∀ (f : Fin (n + 1) → M), ∑ i, f i = ∑ i : Fin n, f i.castSucc + f (Fin.last n)"],
  ["Fin.sum_univ_two", "∀ (f : Fin 2 → M), ∑ i, f i = f 0 + f 1"],
  ["Fin.sum_univ_three", "∀ (f : Fin 3 → M), ∑ i, f i = f 0 + f 1 + f 2"],
  ["Fin.sum_const", "∀ (n : ℕ) (x : M), ∑ _i : Fin n, x = n • x"],
  ["Fin.is_lt", "∀ (a : Fin n), ↑a < n"],
  ["Fin.ext_iff", "a = b ↔ ↑a = ↑b"],
  ["Fin.val_injective", "Function.Injective Fin.val"],
];
